In [ ]:
import numpy as np

创建数组

In [20]:
# help(np.array)

In [3]:
#通过列表创建
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#通过元组创建
np.array((1,2,3))

array([1, 2, 3])

In [8]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
np.array([
    [
        [1,2,3],
        [2,3,4]
    ],[
        [4,5,6],
        [5,6,7]
    ]
])

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [5, 6, 7]]])

In [16]:
#通过zeros创建数组,创建一个元素为零的数组
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
#生成元素为1的三行三列
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.empty((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

其他创建方式

In [22]:
#range
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [24]:
np.arange(9,0,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [25]:
#linspace生成等差数列
np.linspace(1,10,4)

array([  1.,   4.,   7.,  10.])

In [31]:
#logspace 生成等比数列
# np.logspace(0,2,5)  #10的零次方开始，10的2次方结束，生成5个数
np.logspace(0,2,5,base=2)

array([ 1.        ,  1.41421356,  2.        ,  2.82842712,  4.        ])

In [32]:
#使用random创建随机函数
np.random.random((3,3))

array([[ 0.76406296,  0.03760979,  0.81972613],
       [ 0.77287646,  0.21341746,  0.49436889],
       [ 0.41143019,  0.28856758,  0.02598689]])

In [36]:
#生成3,3 的1-9的整数
np.random.randint(1,9,size=(3,3))

array([[8, 7, 7],
       [3, 8, 6],
       [7, 6, 2]])

In [39]:
#标准正态分布
np.random.randn(3,3)

array([[-1.43995724, -0.12712001, -0.59117656],
       [ 0.90049771, -1.67594436, -0.27996404],
       [-1.96293269,  0.36082314,  0.918133  ]])