矩阵切片 索引

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,9,size=(2,3,4))
arr

array([[[7, 4, 8, 6],
        [7, 2, 8, 5],
        [4, 3, 1, 6]],

       [[1, 4, 1, 8],
        [7, 6, 4, 7],
        [8, 7, 3, 1]]])

In [3]:
print(arr[0][0][0])
print(arr[0][0][1])

7
4


In [4]:
print(arr[:,:,1:3])  #1/2维全切，column=all,步数从1到3,步长1
#print(arr[:,:,1:3:1])  #1/2维全切，column=all,步数从1到3,步长1

[[[4 8]
  [2 8]
  [3 1]]

 [[4 1]
  [6 4]
  [7 3]]]


In [5]:
print(arr[:,:,1:3:2])  #1/2维全切，column=all,步数从1到3,步长2

[[[4]
  [2]
  [3]]

 [[4]
  [6]
  [7]]]


In [6]:
print(arr[0,:,1:3])  #切第1维，column=all,步数从1到3，步长1

[[4 8]
 [2 8]
 [3 1]]


In [7]:
print(arr[1,:,1:3])  #切第2维，column=all,步数从1到3，步长1

[[4 1]
 [6 4]
 [7 3]]


In [8]:
print(arr[:,1,1:3]) #1/2维全切，column=1,步数从1到3，步长1

[[2 8]
 [6 4]]


In [9]:
print(arr[:,2,1:3]) #1/2维全切，column=2,步数从1到3，步长1

[[3 1]
 [7 3]]


In [10]:
print(arr[1,2,1:3])

[7 3]


In [11]:
print(arr[0,1:3:2,1:3])

[[2 8]]
