In [1]:
import numpy as np

In [3]:
arr=np.random.randint(1,9,size=(8,4))
arr

array([[8, 6, 8, 4],
       [1, 4, 5, 6],
       [6, 2, 8, 6],
       [1, 8, 7, 8],
       [2, 2, 6, 5],
       [7, 5, 8, 3],
       [6, 6, 8, 3],
       [3, 2, 3, 3]])

In [5]:
#获取0,3,5行数据
print(arr[[0,3,5]])

[[8 6 8 4]
 [1 8 7 8]
 [7 5 8 3]]


In [4]:
#获取第0行第0个，第3行的第3个，第5行的第2个
print(arr[[0,3,5],[0,3,2]])
print(arr[(0,3,5),(0,3,2)])

[8 8 8]
[8 8 8]
