In [1]:
import numpy as np

In [2]:
arr=np.random.random((3,3))
arr

array([[ 0.31424333,  0.70344824,  0.67852688],
       [ 0.52847245,  0.45518121,  0.13154772],
       [ 0.77774323,  0.2848398 ,  0.93698461]])

In [3]:
arr2=arr<0,5
arr2

(array([[False, False, False],
        [False, False, False],
        [False, False, False]], dtype=bool), 5)

In [4]:
name=np.array(['joe','susan','Tom'])
score=np.array([[70,80,90],
               [77,88,99],
                [66,86,97]
                ])
classes=np.array(['math','English','chines'])

In [5]:
name2=name=='joe'
name2

array([ True, False, False], dtype=bool)

In [6]:
score[[True,False,False]]

array([[70, 80, 90]])